sudo: required
language: python
services: docker

install:
  - pip install ansible docker
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles/

script:
  - ansible --version
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory
