ARG VERSION
FROM ubuntu:$VERSION

ADD ansible.gpg /etc/apt/trusted.gpg.d/

RUN . /etc/os-release \
    && echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu $VERSION_CODENAME main" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends ansible \
    && rm -Rf /var/lib/apt/lists/* && apt-get clean

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/lib/systemd/systemd"]